# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - jearm_controller1
    - jearm_controller2

  jearm_controller1:
    type: FollowJointTrajectory
    joints:
      - joint11
      - joint12
      - joint13
      - joint14
      - joint15
      - joint16
      - joint17
    action_ns: follow_joint_trajectory
    default: true
  jearm_controller2:
    type: FollowJointTrajectory
    joints:
      - joint21
      - joint22
      - joint23
      - joint24
      - joint25
      - joint26
      - joint27
    action_ns: follow_joint_trajectory
    default: true