# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    jearm_controller1:
      type: joint_trajectory_controller/JointTrajectoryController


    jearm_controller2:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

jearm_controller1:
  ros__parameters:
    joints:
      - joint11
      - joint12
      - joint13
      - joint14
      - joint15
      - joint16
      - joint17
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
jearm_controller2:
  ros__parameters:
    joints:
      - joint21
      - joint22
      - joint23
      - joint24
      - joint25
      - joint26
      - joint27
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity